### ISSUE TITLE
Making into library option

### ISSUE THREAD

**Issue by garetroy** [GarrettMorrison/C-Bed#7]
An option where ./build (or maybe another script) would be able to compile it all into a library.

**Comment by GarrettMorrison** [comment]
I have added a -l flag to the recmake script that will tell it to generate library files during build. It uses a naive library scheme in that it assumes everything the library needs exists spread across all your source files (excluding your main project file) so if you have functions you need in your main source file or there are source files you don't need you will have to manually modify the CMakeLists (unfortunately no way around that without making things very complicated).

It will build both a static and dynamic library inside build/Lib/<type>/. At some point I would like to add options to specify library type. I am telling it the Lib location as a CMake variable but this shouldn't be changed for now as that location is currently hard-coded into the various scripts. Eventually I would like to fix this (this is also an issue with stuff like BUILD_DIR) so that the user can specify whatever names they want for each directory.
